# Generated by Django 3.2.18 on 2023-02-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('city', models.IntegerField(choices=[(1, 'Warszawa'), (2, 'Poznań'), (3, 'Gdańsk'), (4, 'Katowice'), (5, 'Kraków')], default=1)),
                ('members_amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64)),
                ('task_descr', models.CharField(max_length=64, null=True)),
                ('estimated_time', models.IntegerField(null=True)),
                ('points', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(default='hello_effi123!', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('nickname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='effi_app.user')),
                ('mode', models.IntegerField(choices=[(1, 'remotely'), (2, 'based in city')], default=2)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effi_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('presence', models.BooleanField()),
                ('name_surname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effi_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_infoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_amount', models.IntegerField(null=True)),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effi_app.task')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effi_app.user_info')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='nickname',
            field=models.ManyToManyField(through='effi_app.User_infoTask', to='effi_app.User_info'),
        ),
    ]
