# Generated by Django 3.2.18 on 2023-03-08 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('effi_app', '0002_alter_group_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='nickname',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user_infotask',
            old_name='nickname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user_info',
            name='name_surname',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='username',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='name_surname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effi_app.user_info'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
