# Generated by Django 3.2.18 on 2023-03-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effi_app', '0003_auto_20230308_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='effi_app.group'),
            preserve_default=False,
        ),
    ]
