# Generated by Django 3.2.18 on 2023-03-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effi_app', '0004_task_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_infotask',
            name='owner_amount',
        ),
    ]
