# Generated by Django 3.2.18 on 2023-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effi_app', '0008_alter_user_infotask_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='podtask',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'important'), (2, 'urgent'), (3, 'not urgent')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='task_longdescr',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
