# Generated by Django 3.2.18 on 2023-03-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effi_app', '0010_auto_20230311_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='mode',
        ),
    ]
