# Generated by Django 3.2.18 on 2023-03-11 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effi_app', '0011_remove_user_info_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='effi_app.user_info'),
        ),
    ]
