# Generated by Django 3.2.18 on 2023-03-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effi_app', '0012_alter_task_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
