# Generated by Django 3.2.18 on 2023-03-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effi_app', '0013_user_info_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.IntegerField(null=True)),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effi_app.task')),
            ],
        ),
    ]
