# Generated by Django 3.2.18 on 2023-03-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('effi_app', '0015_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='effi_app.user_info'),
        ),
    ]
