# Generated by Django 3.2.18 on 2023-03-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effi_app', '0017_auto_20230316_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_history',
            name='done',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
