# Generated by Django 3.2.18 on 2023-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effi_app', '0021_remove_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
