# Generated by Django 3.2.18 on 2023-03-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effi_app', '0022_task_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task_history',
        ),
    ]
